//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace FFXIExtractSharp
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<ffxi_items>();
                db.CreateTable<modId>();
            }
        }
    }
    public partial class ffxi_items
    {
        public Int64? item_id { get; set; }
        
        public Int64? flags { get; set; }
        
        public Int64? stack_size { get; set; }
        
        public Int64? ttype { get; set; }
        
        public Int64? resource_id { get; set; }
        
        public Int64? valid_targets { get; set; }
        
        public String en_name { get; set; }
        
        public String en_description { get; set; }
        
        public Int64? level { get; set; }
        
        public Int64? slots { get; set; }
        
        public Int64? races { get; set; }
        
        public Int64? jobs { get; set; }
        
        public Int64? shield_size { get; set; }
        
        public Int64? max_charges { get; set; }
        
        public Int64? casting_time { get; set; }
        
        public Int64? use_delay { get; set; }
        
        public Int64? reuse_delay { get; set; }
        
        public Int64? element { get; set; }
        
        public Int64? storage_slots { get; set; }
        
        public Int64? damage { get; set; }
        
        public Int64? delay { get; set; }
        
        public Int64? dps { get; set; }
        
        public Int64? skill { get; set; }
        
        public Int64? jug_size { get; set; }
        
        public Int64? puppet_slot { get; set; }
        
        public Int64? element_charge { get; set; }
        
        public Int64? rare { get; set; }
        
        public Int64? ex { get; set; }
        
        public Int64? relic { get; set; }
        
        public Int64? item_level { get; set; }
        
        public Int64? superior_level { get; set; }
        
    }
    
    public partial class modId
    {
        public String mod { get; set; }
        
        public Decimal? modid { get; set; }
        
    }
    
}
